#pragma once

// Ignore the second last digit eg c if the version number is a.b.c.d as it is unused

#define FILEVERSION_STRING "49.1.14.18"
#define PRODUCTVERSION_STRING FILEVERSION_STRING
#define MAJORVERSION 1
#define MINORVERSION 14
#define REVISIONVERSION 18

#define FILEVERSION 49,MAJORVERSION,MINORVERSION,REVISIONVERSION
#define PRODUCTVERSION FILEVERSION
